<a href="https://colab.research.google.com/github/vitor-edu/numpy-listas-python-FIAP/blob/master/numpy_e_listas_em_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#Introdução a Python

'''
Duas das principais ferramentas para realizar manipular, tratar, sumarizar e visualizar dados em Python são **Numpy** e **Pandas**. São bibliotecas (conjuntos de classes, funções e objetos) feitos para análise de dados. 

Enquanto Numpy foca em manipulação de vetores e matrizes, muito úteis para realizar operações de álgebra linear (como decomposição de matrizes, calculo de similaridade e distâncias, etc), o Pandas é focado em dados tabulares e manipulações de dados estruturados.
'''

# numpy e listas em python

In [ ]:
lista_de_int = [1,2,3,4,5]
lista_de_string = ["um", "dois", "tres"]
lista_de_listas = [[1,2,2], [1,2], [1,2,3,4]]
lista_mista = [2,4,3, "carro", 8]

Listas são pouco indicadas para fazer contas. 

Suponha que tenhamos duas listas para gerenciar uma compra em uma loja: uma contendo a quantidade de itens, outra o valor dos ítens.


In [ ]:
quantidades = [1, 10, 0, 5, 2]
precos = [10.1, 20.3, 100.75, 0.5, 2.0]



#exercicios
'''
Calcule o preço total da compra do cliente, multiplicando a quantidade pedida do primeiro produto pelo seu preço, a quantidade pedida do segundo produto pelo seu preço e assim por diante.
'''

In [ ]:
quantidades = np.array(quantidades)
precos = np.array(precos)

In [ ]:
quantidades * precos 

array([ 10.1, 203. ,   0. ,   2.5,   4. ])

#### Acessando e mudando elementos do array

Algumas vezes, precisamos acessar (por qualquer motivo que seja) um sub-conjunto de um array do numpy. Pode ser que queiramos usar apenas um elemento (ex.: precisamos mandar para alguém apenas o preço do segundo item). Outras vezes, precisamos de um pedaço maior do array, em outras palavras, um sub-array.

Para acessar apenas um elemento do array, podemos usar a sintaxe `a[i]`. No caso dos preços, por exemplo, podemos acessar o preço do terceiro item fazendo:

In [ ]:
precos[3]

0.5

In [ ]:
precos[0]

10.1

Podemos também usar listas para acessar ***multiplos elementos*** de uma vez, fazendo `a[[1,2,3,4]]`. Por exemplo, se quisermos os preços dos três primeiros itens, podemos fazer:

In [ ]:
precos[[0, 1, 2, 3]]

array([ 10.1 ,  20.3 , 100.75,   0.5 ])

In [ ]:
quantidades[[0, 1, 2, 3, 4]]

array([ 1, 10,  0,  5,  2])

Para acessar ***elementos contíguos (ou seja, adjacentes)*** como no caso acima, podemos também usar o que é chamado de `slicing`. Slices são escritos como `i:j` e significam algo como "acessar os itens da posição `i` (inclusa) até a posição `j` (não inclusa)". Por exemplo, para pegar os preços dos três primeiros itens, faríamos:

In [ ]:
precos[0:3]

array([ 10.1 ,  20.3 , 100.75])

#exercício

Sobre o array `x`, encontre:

* O décimo terceiro elemento
* Um sub-array com o primeiro, terceiro e décimo elemento
* Um sub-array com os 5 primeiros elementos


O décimo terceiro elemento

In [ ]:
x = [1, 2, 3, 4, 55, 65, 65, 44, 34, 23, 45, 45, 65, 54, 67, 90]

In [ ]:
x = np.array(x)

In [ ]:
x[12]

65

Um sub-array com o primeiro, terceiro e décimo elemento

In [ ]:
y = [[1,2], [3,4,55], [65,65,44], [34,23], [45,45], [65,4], [67,90], [3,5,55], [5,65,44], [34,23], [435,45], [645,4], [68,90]]


In [ ]:
y = np.array(y)

In [ ]:
y[[0, 2, 9]]

array([list([1, 2]), list([65, 65, 44]), list([34, 23])], dtype=object)

Um sub-array com os 5 primeiros elementos


In [ ]:
y[:5]

array([list([1, 2]), list([3, 4, 55]), list([65, 65, 44]), list([34, 23]),
       list([45, 45])], dtype=object)

função random(aleatoriedade) - randint(numeros inteiros).

In [ ]:
z = np.random.randint(0, 300, size=10)

In [ ]:
z

array([206,  31,   3, 237,  80, 132, 208, 140, 185, 218])

In [ ]:
z = np.random.randint(0, 500, size=30)

In [ ]:
z

array([ 46, 350, 499, 147, 473, 252, 351, 221, 338, 210, 105, 132, 497,
       110, 183, 250, 234, 178, 113, 144, 125, 427, 194,  66, 415,  79,
       176, 102,  11, 315])

#Máscaras

Para acessar elementos de um array, também podemos usar uma lista de Booleanos (`True` ou `False`) do mesmo tamanho do array. Esta lista é chamada de máscara.

A máscara representa quais elementos você quer preservar (representado por `True`) e quais você quer descartar (`False`) do seu resultado final. Por exemplo, para acessar os preços do primeiro e do terceiro item, fazemos:


In [ ]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 ,   2.  ])

pegar o primeiro e terceiro elemento

In [ ]:
precos[[True, False, True, False, False]]

array([ 10.1 , 100.75])

pegar o quinto elemento.

In [ ]:
precos[[False, False, False, False, True]]

array([2.])

pegar o quarto elemento.

In [ ]:
precos[[False, False, False, True, False]]

array([0.5])


O método da máscara pode parecer inútil, mas é muito útil quando você quer filtrar elementos de um array. Por exemplo, imagine que queremos somente os preços maiores que 10:

In [ ]:
mascara = precos > 10

In [ ]:
mascara

array([ True,  True,  True, False, False])

verificar preços maior que 70.

In [ ]:
mascara = precos > 70

# A máscara é um np.array de booleanos


In [ ]:
mascara

array([False, False,  True, False, False])

# Usamos então a máscara para acessar os elementos que queremos.

In [ ]:
precos[mascara]

array([100.75])

In [ ]:
precos[precos > 10]

array([ 10.1 ,  20.3 , 100.75])

In [ ]:
precos[precos < 3]

array([0.5, 2. ])

In [ ]:
precos[precos < 30]

array([10.1, 20.3,  0.5,  2. ])

#exercicio
Alguns **produtos** tiveram mais de uma unidade pedida pelo usuário (informação que consta na lista *quantidade*). Encontre os *preços* desse produtos.


In [ ]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 ,   2.  ])

In [ ]:
quantidades

array([ 1, 10,  0,  5,  2])

alguns exemplos.

In [ ]:
quantidades > 1

array([False,  True, False,  True,  True])

In [ ]:
quantidades > 7

array([False,  True, False, False, False])

In [ ]:
quantidades >= 0 

array([ True,  True,  True,  True,  True])

In [ ]:
#resultado
precos[quantidades > 1]

array([20.3,  0.5,  2. ])

preço dos produtos acima de 9 itens.

In [ ]:
precos[quantidades > 9]

array([20.3])

# Alterando elementos do array


In [ ]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 ,   2.  ])

In [ ]:
precos[4]

2.0

In [ ]:
precos[4] = 130

In [ ]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 , 130.  ])

Você pode alterar multiplos elementos de uma vez! Imagine que você queira dar um desconto de 50% nos três primeiros itens da lista. Basta fazer:

In [ ]:
precos[0:3] = precos[0:3] / 2

In [ ]:
precos

array([  5.05 ,  10.15 ,  50.375,   0.5  , 130.   ])

# Numpy Arrays de multiplas dimensões

Numpy dá ferramentas excelentes para a manipulação de vetores (no sentido matemático). No entanto, também é ideal quando lidamos com dados de dimensionalidade mais alta, como matrizes ou arrays em 3D. Matrizes, por serem bidimensionais (altura e largura), são capazer de representar objetos como rotações e imagens preto e branco. Arrays 3D podem ser usados para representar imagens coloridas (onde a terceira dimensão é a cor), ou um vídeo (onde a terceira dimensão é o tempo).


In [ ]:
# criando uma matriz
m1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [ ]:
m1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
quantidades

array([ 1, 10,  0,  5,  2])

In [ ]:
precos

array([  5.05 ,  10.15 ,  50.375,   0.5  , 130.   ])

In [ ]:
produtos = [quantidades, precos]

In [ ]:
produtos

[array([ 1, 10,  0,  5,  2]),
 array([  5.05 ,  10.15 ,  50.375,   0.5  , 130.   ])]

#Podemos também criar uma matriz aleatória, fazendo:


In [ ]:
m2 = np.random.randint(0,100, size=(4,3))

In [ ]:
m2

array([[73,  9, 26],
       [65, 36, 36],
       [60, 80, 39],
       [70, 73, 38]])

In [ ]:
m3 = np.random.randint(0,100, size = (10,3))

In [ ]:
m3

array([[29, 33, 95],
       [ 6, 36, 22],
       [29, 75,  2],
       [79, 83, 20],
       [84, 42, 87],
       [74, 10,  4],
       [79, 85, 31],
       [90, 70, 96],
       [73, 13,  3],
       [25, 15, 90]])

In [ ]:
m4 = np.random.randint(0,100, size = (10,3))

In [ ]:
m4

array([[67, 91, 92],
       [ 0, 60, 27],
       [40, 68, 95],
       [86, 22, 46],
       [27, 72, 44],
       [43, 96, 89],
       [38, 62, 30],
       [35, 14, 14],
       [72, 18, 44],
       [89, 92, 55]])

Multiplicação matriccial.

In [ ]:
# np.dot(m3, m4) erro esclarecer duvida.

transpor uma matrix.

In [ ]:
m4.T

array([[67,  0, 40, 86, 27, 43, 38, 35, 72, 89],
       [91, 60, 68, 22, 72, 96, 62, 14, 18, 92],
       [92, 27, 95, 46, 44, 89, 30, 14, 44, 55]])

teste