<a href="https://colab.research.google.com/github/vitor-edu/numpy-listas-python-FIAP/blob/master/numpy_e_listas_em_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#Introdução a Python

'''
Duas das principais ferramentas para realizar manipular, tratar, sumarizar e visualizar dados em Python são **Numpy** e **Pandas**. São bibliotecas (conjuntos de classes, funções e objetos) feitos para análise de dados. 

Enquanto Numpy foca em manipulação de vetores e matrizes, muito úteis para realizar operações de álgebra linear (como decomposição de matrizes, calculo de similaridade e distâncias, etc), o Pandas é focado em dados tabulares e manipulações de dados estruturados.
'''

# numpy e listas em python

In [2]:
lista_de_int = [1,2,3,4,5]
lista_de_string = ["um", "dois", "tres"]
lista_de_listas = [[1,2,2], [1,2], [1,2,3,4]]
lista_mista = [2,4,3, "carro", 8]

Listas são pouco indicadas para fazer contas. 

Suponha que tenhamos duas listas para gerenciar uma compra em uma loja: uma contendo a quantidade de itens, outra o valor dos ítens.


In [3]:
quantidades = [1, 10, 0, 5, 2]
precos = [10.1, 20.3, 100.75, 0.5, 2.0]



#exercicios
'''
Calcule o preço total da compra do cliente, multiplicando a quantidade pedida do primeiro produto pelo seu preço, a quantidade pedida do segundo produto pelo seu preço e assim por diante.
'''

In [4]:
quantidades = np.array(quantidades)
precos = np.array(precos)

In [5]:
quantidades * precos 

array([ 10.1, 203. ,   0. ,   2.5,   4. ])

#### Acessando e mudando elementos do array

Algumas vezes, precisamos acessar (por qualquer motivo que seja) um sub-conjunto de um array do numpy. Pode ser que queiramos usar apenas um elemento (ex.: precisamos mandar para alguém apenas o preço do segundo item). Outras vezes, precisamos de um pedaço maior do array, em outras palavras, um sub-array.

Para acessar apenas um elemento do array, podemos usar a sintaxe `a[i]`. No caso dos preços, por exemplo, podemos acessar o preço do terceiro item fazendo:

In [6]:
precos[3]

0.5

In [7]:
precos[0]

10.1

Podemos também usar listas para acessar ***multiplos elementos*** de uma vez, fazendo `a[[1,2,3,4]]`. Por exemplo, se quisermos os preços dos três primeiros itens, podemos fazer:

In [8]:
precos[[0, 1, 2, 3]]

array([ 10.1 ,  20.3 , 100.75,   0.5 ])

In [9]:
quantidades[[0, 1, 2, 3, 4]]

array([ 1, 10,  0,  5,  2])

Para acessar ***elementos contíguos (ou seja, adjacentes)*** como no caso acima, podemos também usar o que é chamado de `slicing`. Slices são escritos como `i:j` e significam algo como "acessar os itens da posição `i` (inclusa) até a posição `j` (não inclusa)". Por exemplo, para pegar os preços dos três primeiros itens, faríamos:

In [10]:
precos[0:3]

array([ 10.1 ,  20.3 , 100.75])

#exercício

Sobre o array `x`, encontre:

* O décimo terceiro elemento
* Um sub-array com o primeiro, terceiro e décimo elemento
* Um sub-array com os 5 primeiros elementos


O décimo terceiro elemento

In [11]:
x = [1, 2, 3, 4, 55, 65, 65, 44, 34, 23, 45, 45, 65, 54, 67, 90]

In [12]:
x = np.array(x)

In [13]:
x[12]

65

Um sub-array com o primeiro, terceiro e décimo elemento

In [14]:
y = [[1,2], [3,4,55], [65,65,44], [34,23], [45,45], [65,4], [67,90], [3,5,55], [5,65,44], [34,23], [435,45], [645,4], [68,90]]


In [15]:
y = np.array(y)

In [16]:
y[[0, 2, 9]]

array([list([1, 2]), list([65, 65, 44]), list([34, 23])], dtype=object)

Um sub-array com os 5 primeiros elementos


In [17]:
y[:5]

array([list([1, 2]), list([3, 4, 55]), list([65, 65, 44]), list([34, 23]),
       list([45, 45])], dtype=object)

função random(aleatoriedade) - randint(numeros inteiros).

In [18]:
z = np.random.randint(0, 300, size=10)

In [19]:
z

array([ 61, 125,  98, 254, 140,  27, 135,   5,  85, 156])

In [20]:
z = np.random.randint(0, 500, size=30)

In [21]:
z

array([196, 322, 182, 464, 457, 155, 420, 105,  98, 174, 494, 137, 458,
        47,  55, 141, 378, 456, 430, 191,  47, 486, 370,  13, 110, 213,
       182, 380, 446, 215])

#Máscaras

Para acessar elementos de um array, também podemos usar uma lista de Booleanos (`True` ou `False`) do mesmo tamanho do array. Esta lista é chamada de máscara.

A máscara representa quais elementos você quer preservar (representado por `True`) e quais você quer descartar (`False`) do seu resultado final. Por exemplo, para acessar os preços do primeiro e do terceiro item, fazemos:


In [22]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 ,   2.  ])

pegar o primeiro e terceiro elemento

In [23]:
precos[[True, False, True, False, False]]

array([ 10.1 , 100.75])

pegar o quinto elemento.

In [24]:
precos[[False, False, False, False, True]]

array([2.])

pegar o quarto elemento.

In [25]:
precos[[False, False, False, True, False]]

array([0.5])


O método da máscara pode parecer inútil, mas é muito útil quando você quer filtrar elementos de um array. Por exemplo, imagine que queremos somente os preços maiores que 10:

In [26]:
mascara = precos > 10

In [27]:
mascara

array([ True,  True,  True, False, False])

verificar preços maior que 70.

In [94]:
mascara = precos > 70

# A máscara é um np.array de booleanos


In [29]:
mascara

array([False, False,  True, False, False])

# Usamos então a máscara para acessar os elementos que queremos.

In [30]:
precos[mascara]

array([100.75])

In [31]:
precos[precos > 10]

array([ 10.1 ,  20.3 , 100.75])

In [32]:
precos[precos < 3]

array([0.5, 2. ])

In [33]:
precos[precos < 30]

array([10.1, 20.3,  0.5,  2. ])

#exercicio
Alguns **produtos** tiveram mais de uma unidade pedida pelo usuário (informação que consta na lista *quantidade*). Encontre os *preços* desse produtos.


In [34]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 ,   2.  ])

In [35]:
quantidades

array([ 1, 10,  0,  5,  2])

alguns exemplos.

In [36]:
quantidades > 1

array([False,  True, False,  True,  True])

In [37]:
quantidades > 7

array([False,  True, False, False, False])

In [38]:
quantidades >= 0 

array([ True,  True,  True,  True,  True])

In [39]:
#resultado
precos[quantidades > 1]

array([20.3,  0.5,  2. ])

preço dos produtos acima de 9 itens.

In [40]:
precos[quantidades > 9]

array([20.3])

# Alterando elementos do array


In [41]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 ,   2.  ])

In [42]:
precos[4]

2.0

In [43]:
precos[4] = 130

In [44]:
precos

array([ 10.1 ,  20.3 , 100.75,   0.5 , 130.  ])

Você pode alterar multiplos elementos de uma vez! Imagine que você queira dar um desconto de 50% nos três primeiros itens da lista. Basta fazer:

In [45]:
precos[0:3] = precos[0:3] / 2

In [46]:
precos

array([  5.05 ,  10.15 ,  50.375,   0.5  , 130.   ])

# Numpy Arrays de multiplas dimensões

Numpy dá ferramentas excelentes para a manipulação de vetores (no sentido matemático). No entanto, também é ideal quando lidamos com dados de dimensionalidade mais alta, como matrizes ou arrays em 3D. Matrizes, por serem bidimensionais (altura e largura), são capazer de representar objetos como rotações e imagens preto e branco. Arrays 3D podem ser usados para representar imagens coloridas (onde a terceira dimensão é a cor), ou um vídeo (onde a terceira dimensão é o tempo).


In [47]:
# criando uma matriz
m1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [48]:
m1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
quantidades

array([ 1, 10,  0,  5,  2])

In [50]:
precos

array([  5.05 ,  10.15 ,  50.375,   0.5  , 130.   ])

In [51]:
produtos = [quantidades, precos]

In [52]:
produtos

[array([ 1, 10,  0,  5,  2]),
 array([  5.05 ,  10.15 ,  50.375,   0.5  , 130.   ])]

#Podemos também criar uma matriz aleatória, fazendo:


In [53]:
m2 = np.random.randint(0,100, size=(4,3))

In [54]:
m2

array([[63, 47, 74],
       [81, 98, 13],
       [96, 74, 47],
       [88, 89, 87]])

In [55]:
m3 = np.random.randint(0,100, size = (10,3))

In [56]:
m3

array([[63, 75, 60],
       [99, 58, 58],
       [23,  9, 74],
       [37, 64, 57],
       [ 7, 42, 17],
       [84, 53, 90],
       [13, 56, 76],
       [35, 89, 86],
       [91, 77, 65],
       [43, 15, 75]])

In [57]:
m4 = np.random.randint(0,100, size = (10,3))

In [58]:
m4

array([[54, 14, 58],
       [58, 49, 61],
       [87, 71, 19],
       [46, 56, 79],
       [68, 99, 14],
       [63, 34, 16],
       [42, 74,  6],
       [40, 24, 63],
       [41, 86, 33],
       [ 7, 47, 92]])

Multiplicação matriccial.

In [59]:
# np.dot(m3, m4) erro esclarecer duvida.

transpor uma matrix.

In [60]:
m4.T

array([[54, 58, 87, 46, 68, 63, 42, 40, 41,  7],
       [14, 49, 71, 56, 99, 34, 74, 24, 86, 47],
       [58, 61, 19, 79, 14, 16,  6, 63, 33, 92]])

# Acessando dados

Para acessar os dados, basta usar `matriz[linha, coluna]` onde `linha` é a posição da linha e `coluna` é a posição da coluna. Por exemplo, para acessarmos a primeira linha e segunda coluna de uma matriz, fazemos:


In [61]:
m1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
m1[0, 1]

2

In [63]:
m1[1, 2]

6

Técnicas para acessar dados que funcionam para arrays de 1 dimensão, também funcionam aqui. Um exemplo é usar slices:

In [66]:
m1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
m1[0:3, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [72]:
m1[1:4, 0:2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [74]:
m1[1:4, 0:3]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

E também máscaras. Por exemplo, podemos querer só as linhas da matriz cuja segunda coluna tem valor superior a zero:


In [75]:
m1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [76]:
m1[:, :]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
m1[:, 2]

array([ 3,  6,  9, 12])

In [78]:
m1[:, 2] > 7

array([False, False,  True,  True])

In [83]:
m1[:, 2] > 11

array([False, False, False,  True])

In [86]:
mascara = m1[:, 2] > 11
m1[mascara, :]

array([[10, 11, 12]])

#Exercício:

Crie uma matriz do numpy com números aleatórios de 0 a 100. O tamanho da matriz deve ser 100 linhas por 50 colunas. Depois, use a técnica da máscara para selecionar só as linhas da matriz cujo valor da terceira coluna seja maior do que o da primeira coluna. Quantas linhas sobraram?


In [89]:
matrix1 = np.random.randint(0,100, size = (100, 50)) 

In [91]:
matrix1

array([[ 3, 75, 81, ..., 94, 62, 61],
       [89, 47, 41, ..., 26, 61, 42],
       [42, 63, 92, ..., 15, 15, 50],
       ...,
       [ 0, 78, 43, ..., 47, 19, 51],
       [25, 50, 58, ..., 17, 24, 15],
       [74, 25, 83, ..., 69,  7, 66]])

In [93]:
matrix1[:, 3] > matrix1[:, 1] 

array([False, False, False,  True, False,  True,  True, False,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False, False,  True, False,  True,  True, False,
        True, False, False, False,  True,  True, False, False, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
        True, False, False,  True, False, False,  True, False,  True,
       False])

In [95]:
mz = matrix1[:, 3] > matrix1[:, 1] 

In [96]:
mz

array([False, False, False,  True, False,  True,  True, False,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False, False,  True, False,  True,  True, False,
        True, False, False, False,  True,  True, False, False, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
        True, False, False,  True, False, False,  True, False,  True,
       False])

In [97]:
matrix1[mz]

array([[87, 79, 92, ..., 52, 17, 48],
       [88, 10, 63, ..., 36, 94, 15],
       [61,  2, 68, ..., 16, 40, 86],
       ...,
       [61, 16, 90, ..., 82, 59,  6],
       [32, 30, 31, ..., 18, 22, 12],
       [25, 50, 58, ..., 17, 24, 15]])